artifacts_root: artifacts

data_ingestion:
   root_dir: artifacts/data_ingestion
   source_URL: himanshunayal/waferdataset
   local_data_file: artifacts/data_ingestion/waferdataset.zip
   unzip_dir: artifacts/data_ingestion
