artifacts_root: artifacts

data_ingestion:
   root_dir: artifacts/data_ingestion
   source_URL: himanshunayal/waferdataset
   local_data_file: artifacts/data_ingestion/waferdataset.zip
   unzip_dir: artifacts/data_ingestion
   model_input_file: artifacts/data_ingestion/model_input_file.csv

data_preprocessing:
   root_dir: artifacts/data_preprocessing
   model_input_file: artifacts/data_ingestion/model_input_file.csv
   sensor_name_column: Wafer
   label_column_name: Good/Bad
   null_summary_file: artifacts/data_preprocessing/null_columns_summary.csv
   zero_stddev_columns_file: artifacts/data_preprocessing/zero_stddev_columns_file.csv
   preprocessed_model_input_file: artifacts/data_preprocessing/preprocessed_model_input_file.csv
   elbow_plot_file: artifacts/data_preprocessing/kmeans_elbow_plot.png
   kmeans_model_file: artifacts/data_preprocessing/kmeans_model_file.sav

model_training:
   root_dir: artifacts/model_training
   preprocessed_model_input_file: artifacts/data_preprocessing/preprocessed_model_input_file.csv
   cluster_label: Cluster
   label_column_name: Good/Bad
   models_directory: artifacts/model_training/models_directory
