from waferFaultDetection.entity.config_entity import DataIngestionConfig
from waferFaultDetection.entity.config_entity import DataPreprocessingConfig
from waferFaultDetection.entity.config_entity import ModelTrainingConfig